# Generated by Django 5.2.7 on 2025-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
