# Generated by Django 5.2.7 on 2025-11-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_meterreading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
        ),
    ]
