# Generated by Django 5.2.7 on 2025-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_meterreading_rate_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
