# Generated by Django 5.2.7 on 2025-11-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_meterreading_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
