# Generated by Django 5.2.7 on 2025-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_meterreading_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='meter_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
