# Generated by Django 5.2.7 on 2025-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_meterreading_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
