# Generated by Django 5.2.7 on 2025-12-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='created_at',
        ),
        migrations.AddField(
            model_name='receipt',
            name='current_reading',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='meter_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='previous_reading',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='rate_per_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='units_consumed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
